### ISSUE TITLE
Training on images of greater size

### ISSUE THREAD

**Issue by ghost** [2021rahul/colorization_tensorflow#7]
I've tried changing the config file to 
IMAGE_SIZE = 640

and i found one place in the code where 224 was hardcoded and changed that into 640:

self.output = tf.image.resize(logits, [640, 640], method=tf.image.ResizeMethod.NEAREST_NEIGHBOR)

But i get this error message:

Traceback (most recent call last):
  File "/Volumes/TV3/VideoColor/videocolor/SOURCE/main.py", line 31, in <module>
    model.build()
  File "/Volumes/TV3/VideoColor/videocolor/SOURCE/model.py", line 89, in build
    h = fusion_layer.feed_forward(h1, h2, stride=[1, 1, 1, 1])
  File "/Volumes/TV3/VideoColor/videocolor/SOURCE/neural_network.py", line 63, in feed_forward
    fusion_level = tf.reshape(fusion_level, [config.BATCH_SIZE, 28, 28, 512])
  File "/Users/siggi/miniforge3/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/Users/siggi/miniforge3/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 195, in reshape
    result = gen_array_ops.reshape(tensor, shape, name)
  File "/Users/siggi/miniforge3/lib/python3.9/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8397, in reshape
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/Users/siggi/miniforge3/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/Users/siggi/miniforge3/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "/Users/siggi/miniforge3/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2041, in __init__
    self._c_op = _create_c_op(self._graph, node_def, inputs,
  File "/Users/siggi/miniforge3/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1883, in _create_c_op
    raise ValueError(str(e))
ValueError: Cannot reshape a tensor with 3612672 elements to shape [1,28,28,512] (401408 elements) for '{{node Reshape_14114}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](stack, Reshape_14114/shape)' with input shapes: [1,7056,512], [4] and with input tensors computed as partial shapes: input[1] = [1,28,28,512].

I don't have much experience working with neural networks so i'm not really sure exactly what the problem is, but i imagine i have to change some values around so that the network fits the new size? Are there predefined sizes that will work with the network that i should use instead? I've tried multiples of 224 but that doesn't seem to work either.

**Comment by ghost** [comment]
I managed to bypass the error by changing reshape to reshape.(4, 28, 28, 512) and set the image size to 448 (a multiple of 224) It seems that numbers that are not multiples of the original input size will probably not work. But I'm, not exactly sure what effect changing the reshape parameters will have on the network itself.

**Comment by ghost** [comment]
I managed to fix it be changing the reshape function to (1, 56, 56, 512). I think that did the trick.
